apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  labels:
    app: proxy-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: proxy-deployment
      labels:
        app: proxy-deployment
    spec:
      serviceAccountName: proxy-robot
      containers:
        - name: proxy-deployment
          image: wecreateio/proxy
          imagePullPolicy: Always
          env:
            - name: "REMOTE"
              value: "100.127.157.3:32002"
          ports:
            - containerPort: 8080
              name: proxy
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 10m
      restartPolicy: Always
  selector:
    matchLabels:
      app: proxy-deployment
